#!/bin/bash

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/tate/Tate-$VERSION

#echo "Making packages"
#mkdir -pv /root/repo
#git clone https://github.com/mazaclub/tate /root/repo
#cd /root/repo
#git checkout v$VERSION
#cp -v  /root/make_packages /root/repo/make_packages
#cd /root/repo
#mkdir ./packages
#./make_packages
### rm just isn't that expensive to run without fancy bash expansions

#rm -rf /opt/wine-electrum/drive_c/tate/Tate-$VERSION.*
#rm -rf /opt/wine-electrum/drive_c/tate/Tate-$VERSION/
#rm -rf /opt/wine-electrum/drive_c/tate/tate-$VERSION/

#cp -v /root/repo/dist/Tate-$VERSION.zip /opt/wine-electrum/drive_c/tate
#cd /opt/wine-electrum/drive_c/tate
#unzip Tate-$VERSION.zip

cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/tate/deterministic.spec"
cp /opt/wine-electrum/drive_c/tate/tate.nsi $SOURCEDIR/

echo "Running c:/tate/tate-$VERSION/tate.nsi for install"
xvfb-run wine c:\\"Program Files (x86)"\\NSIS\\makensis.exe -V1 c:/tate/tate-$VERSION/tate.nsi


cleanup
